version: "3"

services:
  nginx:
    build: ./nginx/
    container_name: nginx 
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./frontend/app/build/:/usr/share/nginx/html
      - ./nginx/conf/:/etc/nginx/conf.d
      - ./nginx/certificates/:/etc/certs/
    networks:
      - frontend
      - backend 
  prod-backend:
    build: ./backend/
    container_name: prod-backend
    volumes:
      - ./backend/app:/home/app
      - ./nginx/certificates/:/home/certs
      - ${ENTRYPOINT_PATH}:/home/entrypoint_scripts
    entrypoint: /home/entrypoint_scripts/start.sh
    networks:
      - backend
      - frontend
  dev-db:
    container_name: db 
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    networks:
      - backend
networks:
  frontend:
  backend:
