name: Bug Report
description: File a bug report
title: "[Bug] Short description"
labels: ["bug"]
assignees:
  -
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        Please select the relevant label options and milestone
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: The bug is about...
    validations:
      required: true
  - type: textarea
    id: steps-reproduce
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce the behavior
      placeholder: 1- go to [...] | 2- Click on '...' | 3- Scroll down to '...' | 4- Error is on state Y
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: We should see...
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: Desktop or Mobile or both
    validations:
      required: true
  - type: input
    id: OS
    attributes:
      label: OS
      placeholder: iOS8.1, macOS Monterey
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Browser
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: Browser's version
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Anything relevant, it's optional
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
